#!/usr/bin/env bash
[ -z "$1" ] && { echo "USAGE: $(basename "$0") <pid>" 1>&2; exit 1; }

inode="$(stat -c%i /proc/$1)"
[ -n "$inode" ] || exit 0

while [[ "$(stat -c%i /proc/$1 2>/dev/null)" == "$inode" ]]; do
	echo -n .
	sleep 5
done

